openapi: 3.0.0
info:
  title: CST Backend - Prestador API
  version: "1.0.0"
  description: >
    Documentação interativa da API para o módulo Prestador. Esta API gerencia as operações de criação, leitura, atualização, exclusão, importação (Excel) e sincronização com a Omie, bem como o processamento de webhooks provenientes da Omie.
servers:
  - url: http://localhost:4000
security: []  # Sem segurança para visualização
paths:
  /prestadores:
    get:
      summary: Lista todos os prestadores
      operationId: listarPrestadores
      tags:
        - Prestadores
      responses:
        '200':
          description: Lista de prestadores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prestador'
    post:
      summary: Cria um novo prestador
      operationId: criarPrestador
      tags:
        - Prestadores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrestadorInput'
      responses:
        '201':
          description: Prestador criado com sucesso
        '400':
          description: Erro na validação dos dados
  /prestadores/{id}:
    get:
      summary: Obtém um prestador específico
      operationId: obterPrestador
      tags:
        - Prestadores
      parameters:
        - name: id
          in: path
          required: true
          description: ID do prestador
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do prestador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prestador'
        '404':
          description: Prestador não encontrado
  /prestadores/webhook:
    post:
      summary: Processa webhook do Prestador
      operationId: processarPrestadorWebhook
      tags:
        - Prestadores
      responses:
        '200':
          description: Webhook processado com sucesso
        '400':
          description: Erro ao processar webhook
components:
  schemas:
    Prestador:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ID único do prestador
        nome:
          type: string
          description: Nome do prestador
        email:
          type: string
          format: email
          description: Email de contato
        telefone:
          type: string
          description: Número de telefone
        documento:
          type: string
          description: Documento de identificação (CPF/CNPJ)
        endereco:
          type: object
          properties:
            rua:
              type: string
            numero:
              type: string
            complemento:
              type: string
            bairro:
              type: string
            cidade:
              type: string
            estado:
              type: string
            cep:
              type: string
        criadoEm:
          type: string
          format: date-time
        atualizadoEm:
          type: string
          format: date-time
    PrestadorInput:
      type: object
      properties:
        nome:
          type: string
        email:
          type: string
          format: email
        telefone:
          type: string
        documento:
          type: string
        endereco:
          type: object
          properties:
            rua:
              type: string
            numero:
              type: string
            complemento:
              type: string
            bairro:
              type: string
            cidade:
              type: string
            estado:
              type: string
            cep:
              type: string
      required:
        - nome
        - email
        - telefone
        - documento
        - endereco
